# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0002_remove_date_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iframe', models.CharField(max_length=100)),
                ('Attribute', models.CharField(max_length=500)),
            ],
        ),
    ]
